---
# handlers file for webserver
- name: Start firewalld
  systemd:
      name: firewalld
      state: started
      enabled: True

- name: Restart rsyslog
  systemd:
      name: rsyslog
      state: restarted
