---
# vars file for baculamaster
    PG_BACULA_PASSWORD: 8MhrZxsDO50jdQnrqbIn8lrSOnGZI6EE
    FD_PASSWORD: dwykTkKU6am6hWRoLNBT0rBE6NTJKHE4
    DIR_PASSWORD: mOJ8eU11zlQ3hcYN9E49s0Hpm3R6XirN
    SD_PASSWORD: N8mHUKIV7rr9icc0GbAbd985loFeBZ8
    MASTER_ADDRESS: 192.168.11.101
    CLIENT_ADDRESS: 192.168.11.102
